import { hexToRgb565, mappedHardwareIndex, safeFileName, type PixelProject } from "@/lib/pixel";

export type CodeExportFormat = "json" | "micropython" | "arduino";

const physicalFrames = (project: PixelProject): number[][] => project.frames.map((frame) => {
  const output = Array.from({ length: project.width * project.height }, () => 0);
  frame.forEach((color, logicalIndex) => {
    const x = logicalIndex % project.width;
    const y = Math.floor(logicalIndex / project.width);
    output[mappedHardwareIndex(x, y, project)] = hexToRgb565(color);
  });
  return output;
});

const rows = (values: number[], width = 12) => {
  const lines: string[] = [];
  for (let index = 0; index < values.length; index += width) {
    lines.push(`        ${values.slice(index, index + width).map((value) => `0x${value.toString(16).padStart(4, "0").toUpperCase()}`).join(", ")}`);
  }
  return lines.join(",\n");
};

export const toMicroPythonCode = (project: PixelProject): string => {
  const order = [...project.pixel_order].map((channel) => "RGB".indexOf(channel)).join(", ");
  const frames = physicalFrames(project).map((frame, index) => `    (  # ${(project.frame_names[index] ?? `Frame ${index + 1}`).replace(/[\r\n]/g, " ")}\n${rows(frame)}\n    )`).join(",\n");
  const durations = project.frame_durations.map((value) => Math.max(100, Math.round(value))).join(", ");
  return `# Generated by PixelSky — save as main.py on the XIAO ESP32-C3
from machine import Pin
import neopixel
import time

DATA_PIN = ${project.pin}
PIXEL_COUNT = ${project.width * project.height}
BRIGHTNESS = ${(project.brightness / 500).toFixed(4)}  # safe physical output, max 0.2
GAMMA = ${project.gamma.toFixed(2)}
CHANNEL_BALANCE = (${project.r_balance.toFixed(2)}, ${project.g_balance.toFixed(2)}, ${project.b_balance.toFixed(2)})
LOOP = ${project.loop ? "True" : "False"}
DURATIONS_MS = (${durations},)
FRAMES = [\n${frames}\n]

strip = neopixel.NeoPixel(Pin(DATA_PIN, Pin.OUT), PIXEL_COUNT)
strip.ORDER = (${order})

def rgb565(value):
    r = ((value >> 11) & 0x1f) * 255 // 31
    g = ((value >> 5) & 0x3f) * 255 // 63
    b = (value & 0x1f) * 255 // 31
    channels = (r, g, b)
    return tuple(min(255, int(((channel / 255) ** GAMMA) * 255 * BRIGHTNESS * CHANNEL_BALANCE[index])) for index, channel in enumerate(channels))

def show(frame):
    for index, color in enumerate(frame):
        strip[index] = rgb565(color)
    strip.write()

while True:
    for index, frame in enumerate(FRAMES):
        show(frame)
        time.sleep_ms(DURATIONS_MS[index])
    if not LOOP:
        while True:
            time.sleep_ms(1000)
`;
};

export const toArduinoCode = (project: PixelProject): string => {
  const frames = physicalFrames(project).map((frame, index) => `  { // ${(project.frame_names[index] ?? `Frame ${index + 1}`).replace(/[\r\n]/g, " ")}\n${rows(frame)}\n  }`).join(",\n");
  const durations = project.frame_durations.map((value) => Math.max(100, Math.round(value))).join(", ");
  const brightness = Math.max(1, Math.round(project.brightness * 0.51));
  return `// Generated by PixelSky for ESP32 / XIAO ESP32-C3
#include <Adafruit_NeoPixel.h>

constexpr uint8_t DATA_PIN = ${project.pin};
constexpr uint16_t PIXEL_COUNT = ${project.width * project.height};
constexpr uint8_t FRAME_COUNT = ${project.frames.length};
constexpr uint8_t BRIGHTNESS = ${brightness}; // safe maximum is 51/255
constexpr float GAMMA_VALUE = ${project.gamma.toFixed(2)}f;
const float CHANNEL_BALANCE[3] = { ${project.r_balance.toFixed(2)}f, ${project.g_balance.toFixed(2)}f, ${project.b_balance.toFixed(2)}f };
constexpr bool LOOP_ANIMATION = ${project.loop ? "true" : "false"};

Adafruit_NeoPixel strip(PIXEL_COUNT, DATA_PIN, NEO_${project.pixel_order} + NEO_KHZ800);
const uint16_t DURATIONS_MS[FRAME_COUNT] = { ${durations} };
const uint16_t FRAMES[FRAME_COUNT][PIXEL_COUNT] PROGMEM = {\n${frames}\n};

uint8_t correctChannel(uint8_t value, uint8_t channel) {
  float corrected = pow(value / 255.0f, GAMMA_VALUE) * 255.0f * CHANNEL_BALANCE[channel];
  return (uint8_t)constrain(corrected, 0.0f, 255.0f);
}

void showFrame(uint8_t frameIndex) {
  for (uint16_t index = 0; index < PIXEL_COUNT; ++index) {
    uint16_t value = pgm_read_word(&FRAMES[frameIndex][index]);
    uint8_t r = ((value >> 11) & 0x1F) * 255 / 31;
    uint8_t g = ((value >> 5) & 0x3F) * 255 / 63;
    uint8_t b = (value & 0x1F) * 255 / 31;
    strip.setPixelColor(index, strip.Color(correctChannel(r, 0), correctChannel(g, 1), correctChannel(b, 2)));
  }
  strip.show();
}

void setup() {
  strip.begin();
  strip.setBrightness(BRIGHTNESS);
  strip.clear();
  strip.show();
}

void loop() {
  static uint8_t frameIndex = 0;
  showFrame(frameIndex);
  delay(DURATIONS_MS[frameIndex]);
  if (++frameIndex >= FRAME_COUNT) {
    if (LOOP_ANIMATION) frameIndex = 0;
    else while (true) delay(1000);
  }
}
`;
};

export const downloadText = (filename: string, value: string, type = "text/plain;charset=utf-8") => {
  const blob = new Blob([value], { type });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  anchor.click();
  URL.revokeObjectURL(url);
};

export const codeFilename = (project: PixelProject, format: Exclude<CodeExportFormat, "json">) =>
  `${safeFileName(project.name)}.${format === "micropython" ? "py" : "ino"}`;
